/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Lucas
 */
public class GUI_HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public GUI_HomeScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_CreateCouple = new javax.swing.JButton();
        JB_LoadCouple = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contraceptive Method Choice");

        JB_CreateCouple.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        JB_CreateCouple.setAlignmentX(0.5F);
        JB_CreateCouple.setLabel("Create New Couple");
        JB_CreateCouple.setMaximumSize(new java.awt.Dimension(175, 40));
        JB_CreateCouple.setName("JB_CreateCouple"); // NOI18N
        JB_CreateCouple.setSize(new java.awt.Dimension(100, 40));
        JB_CreateCouple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CreateCoupleActionPerformed(evt);
            }
        });

        JB_LoadCouple.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        JB_LoadCouple.setText("Load Couples File");
        JB_LoadCouple.setAlignmentX(0.5F);
        JB_LoadCouple.setMaximumSize(new java.awt.Dimension(175, 40));
        JB_LoadCouple.setName("JB_CreateNewCouple"); // NOI18N
        JB_LoadCouple.setSize(new java.awt.Dimension(100, 40));
        JB_LoadCouple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LoadCoupleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_LoadCouple, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_CreateCouple, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(JB_CreateCouple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_LoadCouple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_CreateCoupleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CreateCoupleActionPerformed
        GUI_CreateCouple createCouple = GUI_CreateCouple.getGUI_CreateCouple();
        createCouple.setVisible(true);
    }//GEN-LAST:event_JB_CreateCoupleActionPerformed

    private void JB_LoadCoupleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LoadCoupleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_LoadCoupleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_CreateCouple;
    private javax.swing.JButton JB_LoadCouple;
    // End of variables declaration//GEN-END:variables
}
