/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Lucas
 */
public class GUI_CreateCouple extends javax.swing.JFrame {

    /**
     * Creates new form CreateCouple
     */
    public GUI_CreateCouple() {
        initComponents();
        setItems();
        this.setLocationRelativeTo(null);
        
    }
    
    private static GUI_CreateCouple createCouple = null;
    
    public static GUI_CreateCouple getGUI_CreateCouple()
    {
        if(createCouple == null)
            createCouple = new GUI_CreateCouple();
        
        return createCouple;
            
    }
    
    private void setItems() {
        /*Vector model = new Vector();
        model.addElement( new Item(1, "low" ) );
        model.addElement( new Item(2, "medium" ) );
        model.addElement( new Item(3, "regular" ) );
        model.addElement( new Item(4, "high" ) );
 
        JComboBox comboBox;*/
 
        //  Easiest approach is to just override toString() method
        //  of the Item class
 
        //comboBox = new JComboBox( model );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLWifeAge = new javax.swing.JLabel();
        jLWifeEducation = new javax.swing.JLabel();
        jLHusbandEducation = new javax.swing.JLabel();
        jLNumberChildren = new javax.swing.JLabel();
        jLWifeReligion = new javax.swing.JLabel();
        jLWifeWork = new javax.swing.JLabel();
        jLHusbandOccupation = new javax.swing.JLabel();
        jLStandardLivingIndex = new javax.swing.JLabel();
        jLMediaExposure = new javax.swing.JLabel();
        jLContraceptiveMethod = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCBWifeEducation = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jCBStatusAcademia = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Couple");

        jLWifeAge.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLWifeAge.setText("Wife's Age");

        jLWifeEducation.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLWifeEducation.setText("Wife's Education");

        jLHusbandEducation.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLHusbandEducation.setText("Husband's Education");

        jLNumberChildren.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLNumberChildren.setText("Number of children even born");

        jLWifeReligion.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLWifeReligion.setText("Wife's religion ");

        jLWifeWork.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLWifeWork.setText("Wife's now working?");

        jLHusbandOccupation.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLHusbandOccupation.setText("Husband's occupation");

        jLStandardLivingIndex.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLStandardLivingIndex.setText("Standard-of-living index");

        jLMediaExposure.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLMediaExposure.setText("Media exposure");

        jLContraceptiveMethod.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLContraceptiveMethod.setText("Contraceptive method used");

        jTextField1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jCBWifeEducation.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCBWifeEducation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "j" }));
        jCBWifeEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBWifeEducationActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Yes");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("No");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "low", "medium", "regular", "high", " " }));

        jCBStatusAcademia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fechada", "Aberta", "Em Balanço" }));
        jCBStatusAcademia.setEnabled(false);
        jCBStatusAcademia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBStatusAcademiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLContraceptiveMethod)
                    .addComponent(jLWifeEducation)
                    .addComponent(jLWifeAge)
                    .addComponent(jLHusbandEducation)
                    .addComponent(jLNumberChildren)
                    .addComponent(jLWifeReligion)
                    .addComponent(jLWifeWork)
                    .addComponent(jLHusbandOccupation)
                    .addComponent(jLStandardLivingIndex)
                    .addComponent(jLMediaExposure))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1)
                        .addComponent(jCBWifeEducation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton4))
                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox4, 0, 158, Short.MAX_VALUE))
                    .addComponent(jCBStatusAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLWifeAge)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLWifeEducation)
                    .addComponent(jCBWifeEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLHusbandEducation)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumberChildren)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLWifeReligion)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLWifeWork)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLHusbandOccupation)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLStandardLivingIndex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLMediaExposure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLContraceptiveMethod))
                    .addComponent(jCBStatusAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jCBStatusAcademiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBStatusAcademiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBStatusAcademiaActionPerformed

    private void jCBWifeEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBWifeEducationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBWifeEducationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_CreateCouple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_CreateCouple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_CreateCouple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_CreateCouple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_CreateCouple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jCBStatusAcademia;
    private javax.swing.JComboBox jCBWifeEducation;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLContraceptiveMethod;
    private javax.swing.JLabel jLHusbandEducation;
    private javax.swing.JLabel jLHusbandOccupation;
    private javax.swing.JLabel jLMediaExposure;
    private javax.swing.JLabel jLNumberChildren;
    private javax.swing.JLabel jLStandardLivingIndex;
    private javax.swing.JLabel jLWifeAge;
    private javax.swing.JLabel jLWifeEducation;
    private javax.swing.JLabel jLWifeReligion;
    private javax.swing.JLabel jLWifeWork;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
