/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import contraceptiveMethodChoice.Couple;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;


/**
 *
 * @author Lucas
 */
public class GUI_CreateCouple extends javax.swing.JFrame {


    /**
     * Creates new form CreateCouple
     */
    public GUI_CreateCouple() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jLContraceptiveMethod.setVisible(false);
        jCBContraceptiveMethod.setVisible(false);
        jLDescription9.setVisible(false);
    }
    
    private static GUI_CreateCouple createCouple = null;
    
    public static GUI_CreateCouple getGUI_CreateCouple()
    {
        if(createCouple == null)
            createCouple = new GUI_CreateCouple();
        
        return createCouple;
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGWifeReligion = new javax.swing.ButtonGroup();
        bGWifeWork = new javax.swing.ButtonGroup();
        bGMediaExposure = new javax.swing.ButtonGroup();
        jLWifeAge = new javax.swing.JLabel();
        jLWifeEducation = new javax.swing.JLabel();
        jLHusbandEducation = new javax.swing.JLabel();
        jLNumberChildren = new javax.swing.JLabel();
        jLWifeReligion = new javax.swing.JLabel();
        jLWifeWork = new javax.swing.JLabel();
        jLHusbandOccupation = new javax.swing.JLabel();
        jLStandardLivingIndex = new javax.swing.JLabel();
        jLMediaExposure = new javax.swing.JLabel();
        jLContraceptiveMethod = new javax.swing.JLabel();
        jTFWifeAge = new javax.swing.JTextField();
        jCBWifeEducation = new javax.swing.JComboBox();
        jTFNumberChildren = new javax.swing.JTextField();
        jRBWifeReligionF = new javax.swing.JRadioButton();
        jRBWifeReligionT = new javax.swing.JRadioButton();
        jCBHusbandEducation = new javax.swing.JComboBox();
        jCBHusbandOccupation = new javax.swing.JComboBox();
        jCBStandardLivingIndex = new javax.swing.JComboBox();
        jCBContraceptiveMethod = new javax.swing.JComboBox();
        jLDescription0 = new javax.swing.JLabel();
        jLDescription1 = new javax.swing.JLabel();
        jLDescription3 = new javax.swing.JLabel();
        jLDescription4 = new javax.swing.JLabel();
        jLDescription5 = new javax.swing.JLabel();
        jLDescription6 = new javax.swing.JLabel();
        jLDescription7 = new javax.swing.JLabel();
        jLDescription8 = new javax.swing.JLabel();
        jLDescription9 = new javax.swing.JLabel();
        jLDescription2 = new javax.swing.JLabel();
        jRBWifeWorkF = new javax.swing.JRadioButton();
        jRBWifeWorkT = new javax.swing.JRadioButton();
        jRBMediaExposureF = new javax.swing.JRadioButton();
        jRBMediaExposureT = new javax.swing.JRadioButton();
        jBCreateCouple = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Couple");

        jLWifeAge.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLWifeAge.setText("Wife's Age");

        jLWifeEducation.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLWifeEducation.setText("Wife's Education");

        jLHusbandEducation.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLHusbandEducation.setText("Husband's Education");

        jLNumberChildren.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLNumberChildren.setText("Number of children even born");

        jLWifeReligion.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLWifeReligion.setText("Wife's religion ");

        jLWifeWork.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLWifeWork.setText("Wife's now working?");

        jLHusbandOccupation.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLHusbandOccupation.setText("Husband's occupation");

        jLStandardLivingIndex.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLStandardLivingIndex.setText("Standard-of-living index");

        jLMediaExposure.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLMediaExposure.setText("Media exposure");

        jLContraceptiveMethod.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLContraceptiveMethod.setText("Contraceptive method used");

        jTFWifeAge.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTFWifeAge.setText("30");
        jTFWifeAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFWifeAgeActionPerformed(evt);
            }
        });

        jCBWifeEducation.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCBWifeEducation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jCBWifeEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBWifeEducationActionPerformed(evt);
            }
        });

        jTFNumberChildren.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTFNumberChildren.setText("0");
        jTFNumberChildren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumberChildrenActionPerformed(evt);
            }
        });

        bGWifeReligion.add(jRBWifeReligionF);
        jRBWifeReligionF.setMnemonic('f');
        jRBWifeReligionF.setSelected(true);
        jRBWifeReligionF.setText("false");
        jRBWifeReligionF.setActionCommand("FALSE");
        jRBWifeReligionF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBWifeReligionFActionPerformed(evt);
            }
        });

        bGWifeReligion.add(jRBWifeReligionT);
        jRBWifeReligionT.setMnemonic('t');
        jRBWifeReligionT.setText("true");
        jRBWifeReligionT.setActionCommand("TRUE");
        jRBWifeReligionT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBWifeReligionTActionPerformed(evt);
            }
        });

        jCBHusbandEducation.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCBHusbandEducation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jCBHusbandEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBHusbandEducationActionPerformed(evt);
            }
        });

        jCBHusbandOccupation.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCBHusbandOccupation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jCBHusbandOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBHusbandOccupationActionPerformed(evt);
            }
        });

        jCBStandardLivingIndex.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCBStandardLivingIndex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jCBStandardLivingIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBStandardLivingIndexActionPerformed(evt);
            }
        });

        jCBContraceptiveMethod.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jCBContraceptiveMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        jCBContraceptiveMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBContraceptiveMethodActionPerformed(evt);
            }
        });

        jLDescription0.setFont(new java.awt.Font("Helvetica", 2, 10)); // NOI18N
        jLDescription0.setText("(integer)");

        jLDescription1.setFont(new java.awt.Font("Helvetica", 2, 10)); // NOI18N
        jLDescription1.setText("1=low, 2=medium, 3=regular, 4=high");

        jLDescription3.setFont(new java.awt.Font("Helvetica", 2, 10)); // NOI18N
        jLDescription3.setText("0=Non-Islam (False), 1=Islam (True)");

        jLDescription4.setFont(new java.awt.Font("Helvetica", 2, 10)); // NOI18N
        jLDescription4.setText("(integer)");

        jLDescription5.setFont(new java.awt.Font("Helvetica", 2, 10)); // NOI18N
        jLDescription5.setText("0=Yes (False), 1=No (True)");

        jLDescription6.setFont(new java.awt.Font("Helvetica", 2, 10)); // NOI18N
        jLDescription6.setText("1=low, 2=medium, 3=regular, 4=high");

        jLDescription7.setFont(new java.awt.Font("Helvetica", 2, 10)); // NOI18N
        jLDescription7.setText("1=low, 2=medium, 3=regular, 4=high");

        jLDescription8.setFont(new java.awt.Font("Helvetica", 2, 10)); // NOI18N
        jLDescription8.setText("0=Good (False), 1=Not good (True)");

        jLDescription9.setFont(new java.awt.Font("Helvetica", 2, 10)); // NOI18N
        jLDescription9.setText("1=No-use, 2=Long-term, 3=Short-term");

        jLDescription2.setFont(new java.awt.Font("Helvetica", 2, 10)); // NOI18N
        jLDescription2.setText("1=low, 2=medium, 3=regular, 4=high");

        bGWifeWork.add(jRBWifeWorkF);
        jRBWifeWorkF.setSelected(true);
        jRBWifeWorkF.setText("false");
        jRBWifeWorkF.setActionCommand("FALSE");
        jRBWifeWorkF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBWifeWorkFActionPerformed(evt);
            }
        });

        bGWifeWork.add(jRBWifeWorkT);
        jRBWifeWorkT.setText("true");
        jRBWifeWorkT.setActionCommand("TRUE");
        jRBWifeWorkT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBWifeWorkTActionPerformed(evt);
            }
        });

        bGMediaExposure.add(jRBMediaExposureF);
        jRBMediaExposureF.setSelected(true);
        jRBMediaExposureF.setText("false");
        jRBMediaExposureF.setActionCommand("FALSE");
        jRBMediaExposureF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMediaExposureFActionPerformed(evt);
            }
        });

        bGMediaExposure.add(jRBMediaExposureT);
        jRBMediaExposureT.setText("true");
        jRBMediaExposureT.setActionCommand("TRUE");
        jRBMediaExposureT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMediaExposureTActionPerformed(evt);
            }
        });

        jBCreateCouple.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jBCreateCouple.setText("Save");
        jBCreateCouple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreateCoupleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLContraceptiveMethod)
                            .addComponent(jLWifeEducation)
                            .addComponent(jLWifeAge)
                            .addComponent(jLHusbandEducation)
                            .addComponent(jLNumberChildren)
                            .addComponent(jLWifeReligion)
                            .addComponent(jLWifeWork)
                            .addComponent(jLHusbandOccupation)
                            .addComponent(jLStandardLivingIndex)
                            .addComponent(jLMediaExposure))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTFWifeAge)
                                .addComponent(jCBWifeEducation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFNumberChildren)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRBWifeReligionF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRBWifeReligionT))
                                .addComponent(jCBHusbandEducation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBHusbandOccupation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBStandardLivingIndex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCBContraceptiveMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBWifeWorkF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBWifeWorkT))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBMediaExposureF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRBMediaExposureT)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLDescription6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLDescription0, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLDescription4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLDescription9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(jLDescription5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLDescription3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLDescription1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLDescription7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLDescription8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBCreateCouple, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLWifeAge)
                    .addComponent(jTFWifeAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescription0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLWifeEducation)
                    .addComponent(jCBWifeEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescription1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLHusbandEducation)
                    .addComponent(jCBHusbandEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescription2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumberChildren)
                    .addComponent(jTFNumberChildren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescription4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLWifeReligion)
                    .addComponent(jRBWifeReligionF)
                    .addComponent(jRBWifeReligionT)
                    .addComponent(jLDescription3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLWifeWork)
                    .addComponent(jLDescription5)
                    .addComponent(jRBWifeWorkF)
                    .addComponent(jRBWifeWorkT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLHusbandOccupation)
                    .addComponent(jCBHusbandOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescription6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStandardLivingIndex)
                    .addComponent(jCBStandardLivingIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescription7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMediaExposure)
                    .addComponent(jLDescription8)
                    .addComponent(jRBMediaExposureF)
                    .addComponent(jRBMediaExposureT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLContraceptiveMethod)
                    .addComponent(jCBContraceptiveMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescription9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCreateCouple, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFWifeAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFWifeAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFWifeAgeActionPerformed

    private void jTFNumberChildrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumberChildrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumberChildrenActionPerformed

    private void jRBWifeReligionFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBWifeReligionFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBWifeReligionFActionPerformed

    private void jRBWifeReligionTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBWifeReligionTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBWifeReligionTActionPerformed

    private void jCBWifeEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBWifeEducationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBWifeEducationActionPerformed

    private void jCBHusbandEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBHusbandEducationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBHusbandEducationActionPerformed

    private void jCBHusbandOccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBHusbandOccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBHusbandOccupationActionPerformed

    private void jCBStandardLivingIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBStandardLivingIndexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBStandardLivingIndexActionPerformed

    private void jRBWifeWorkFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBWifeWorkFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBWifeWorkFActionPerformed

    private void jRBWifeWorkTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBWifeWorkTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBWifeWorkTActionPerformed

    private void jRBMediaExposureFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMediaExposureFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBMediaExposureFActionPerformed

    private void jRBMediaExposureTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMediaExposureTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBMediaExposureTActionPerformed

    private void jBCreateCoupleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreateCoupleActionPerformed
        
        try {
            
            // Instance's Data
            Couple couple = new Couple();

            couple.setWifeAge( Integer.parseInt( jTFWifeAge.getText() ) );
            couple.setWifeEducation( Short.parseShort( jCBWifeEducation.getSelectedItem().toString() ) );
            couple.setHusbandEducation(Short.parseShort( jCBHusbandEducation.getSelectedItem().toString() ));
            couple.setNumberChildren( Integer.parseInt( jTFNumberChildren.getText() ) );
            couple.setWifeReligion( Boolean.parseBoolean( bGWifeReligion.getSelection().getActionCommand() ) );
            couple.setWifeWork( Boolean.parseBoolean( bGWifeWork.getSelection().getActionCommand() ) );
            couple.setHusbandOccupation( Short.parseShort( jCBHusbandOccupation.getSelectedItem().toString() ) );
            couple.setStandardLivingIndex( Short.parseShort( jCBStandardLivingIndex.getSelectedItem().toString() ) );
            couple.setMediaExposure( Boolean.parseBoolean( bGMediaExposure.getSelection().getActionCommand() ) );
            /*
                couple.setContraceptiveMethod( Short.parseShort( jCBContraceptiveMethod.getSelectedItem().toString() ) );
                short noClass = -1;
                couple.setContraceptiveMethod( noClass );
            */
            
            
            //JOptionPane.showMessageDialog(null, couple.showCouple());
            
            int reply = JOptionPane.showConfirmDialog(null, 
                    "Are you about the data?" + "\n" + couple.showCouple(), 
                    "Alert", 
                    JOptionPane.YES_NO_OPTION);
            if(reply == JOptionPane.YES_OPTION)
                returnHomeScreen(couple);
        }
        catch(NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, 
                    e,
                    "Error!",
                    JOptionPane.ERROR_MESSAGE
                    );
        }
    }//GEN-LAST:event_jBCreateCoupleActionPerformed

    private void jCBContraceptiveMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBContraceptiveMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBContraceptiveMethodActionPerformed

    
    private void returnHomeScreen(Couple couple) {
        GUI_HomeScreen homeScreen = new GUI_HomeScreen(couple);
        homeScreen.setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_CreateCouple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_CreateCouple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_CreateCouple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_CreateCouple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_CreateCouple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGMediaExposure;
    private javax.swing.ButtonGroup bGWifeReligion;
    private javax.swing.ButtonGroup bGWifeWork;
    private javax.swing.JButton jBCreateCouple;
    private javax.swing.JComboBox jCBContraceptiveMethod;
    private javax.swing.JComboBox jCBHusbandEducation;
    private javax.swing.JComboBox jCBHusbandOccupation;
    private javax.swing.JComboBox jCBStandardLivingIndex;
    private javax.swing.JComboBox jCBWifeEducation;
    private javax.swing.JLabel jLContraceptiveMethod;
    private javax.swing.JLabel jLDescription0;
    private javax.swing.JLabel jLDescription1;
    private javax.swing.JLabel jLDescription2;
    private javax.swing.JLabel jLDescription3;
    private javax.swing.JLabel jLDescription4;
    private javax.swing.JLabel jLDescription5;
    private javax.swing.JLabel jLDescription6;
    private javax.swing.JLabel jLDescription7;
    private javax.swing.JLabel jLDescription8;
    private javax.swing.JLabel jLDescription9;
    private javax.swing.JLabel jLHusbandEducation;
    private javax.swing.JLabel jLHusbandOccupation;
    private javax.swing.JLabel jLMediaExposure;
    private javax.swing.JLabel jLNumberChildren;
    private javax.swing.JLabel jLStandardLivingIndex;
    private javax.swing.JLabel jLWifeAge;
    private javax.swing.JLabel jLWifeEducation;
    private javax.swing.JLabel jLWifeReligion;
    private javax.swing.JLabel jLWifeWork;
    private javax.swing.JRadioButton jRBMediaExposureF;
    private javax.swing.JRadioButton jRBMediaExposureT;
    private javax.swing.JRadioButton jRBWifeReligionF;
    private javax.swing.JRadioButton jRBWifeReligionT;
    private javax.swing.JRadioButton jRBWifeWorkF;
    private javax.swing.JRadioButton jRBWifeWorkT;
    private javax.swing.JTextField jTFNumberChildren;
    private javax.swing.JTextField jTFWifeAge;
    // End of variables declaration//GEN-END:variables
}
